### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "com.intellij.psi.PsiDirectory.getFiles()" because "d" is null

### ISSUE THREAD

**Issue by Kevin3112** [isselab/HAnS#18]
### What happened?

While working with HAnS, a NullPointerException was thrown with no clear indication on why. It's currently unknown what exactly leads to the error. The stack trace suggests, that either a file of a PsiElement or a directory of a file could not be found. HAnS was still working after the bug occured.

### Relevant log output or stack trace

```shell
java.lang.NullPointerException: Cannot invoke "com.intellij.psi.PsiDirectory.getFiles()" because "d" is null

    at se.isselab.HAnS.referencing.FileReferenceUtil.findFiles(FileReferenceUtil.java:47)

    at se.isselab.HAnS.referencing.FileReference.getVariants(FileReference.java:58)

    at com.intellij.codeInsight.completion.CompletionData.completeReference(CompletionData.java:222)

    at com.intellij.codeInsight.completion.CompletionVariant.addReferenceCompletions(CompletionVariant.java:122)

    at com.intellij.codeInsight.completion.CompletionData.completeReference(CompletionData.java:63)

    at com.intellij.codeInsight.completion.LegacyCompletionContributor.lambda$completeReference$0(LegacyCompletionContributor.java:80)

    at com.intellij.codeInsight.completion.LegacyCompletionContributor.processReference(LegacyCompletionContributor.java:141)

    at com.intellij.codeInsight.completion.LegacyCompletionContributor.processReferences(LegacyCompletionContributor.java:124)

    at com.intellij.codeInsight.completion.LegacyCompletionContributor.completeReference(LegacyCompletionContributor.java:78)

    at com.intellij.codeInsight.completion.LegacyCompletionContributor.fillCompletionVariants(LegacyCompletionContributor.java:48)

    at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributor(CompletionService.java:81)

    at com.intellij.codeInsight.completion.impl.CompletionServiceImpl.lambda$getVariantsFromContributor$0(CompletionServiceImpl.java:327)

    at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.runWithSpan(trace.kt:80)

    at com.intellij.codeInsight.completion.impl.CompletionServiceImpl.getVariantsFromContributor(CompletionServiceImpl.java:326)

    at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:73)

    at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:150)

    at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:142)

    at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:138)

    at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$1.addCompletions(LiveTemplateCompletionContributor.java:87)

    at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:23)

    at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:155)

    at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributor(CompletionService.java:81)

    at com.intellij.codeInsight.completion.impl.CompletionServiceImpl.lambda$getVariantsFromContributor$0(CompletionServiceImpl.java:327)

    at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.runWithSpan(trace.kt:80)

    at com.intellij.codeInsight.completion.impl.CompletionServiceImpl.getVariantsFromContributor(CompletionServiceImpl.java:326)

    at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:73)

    at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:56)

    at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:130)

    at com.intellij.codeInsight.completion.BaseCompletionService.performCompletion(BaseCompletionService.java:48)

    at com.intellij.codeInsight.completion.impl.CompletionServiceImpl.lambda$performCompletion$1(CompletionServiceImpl.java:345)

    at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.runWithSpan(trace.kt:80)

    at com.intellij.codeInsight.completion.impl.CompletionServiceImpl.performCompletion(CompletionServiceImpl.java:334)

    at com.intellij.codeInsight.completion.CompletionProgressIndicator.lambda$calculateItems$12(CompletionProgressIndicator.java:961)

    at com.intellij.util.indexing.FileBasedIndex.lambda$ignoreDumbMode$0(FileBasedIndex.java:219)

    at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)

    at com.intellij.util.indexing.FileBasedIndexEx.ignoreDumbMode(FileBasedIndexEx.java:644)

    at com.intellij.util.indexing.FileBasedIndex.ignoreDumbMode(FileBasedIndex.java:218)

    at com.intellij.util.indexing.DumbModeAccessType.ignoreDumbMode(DumbModeAccessType.java:43)

    at com.intellij.codeInsight.completion.CompletionProgressIndicator.calculateItems(CompletionProgressIndicator.java:957)

    at com.intellij.codeInsight.completion.CompletionProgressIndicator.runContributors(CompletionProgressIndicator.java:945)

    at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$startContributorThread$7(CodeCompletionHandlerBase.java:378)

    at io.opentelemetry.context.Context.lambda$wrap$1(Context.java:212)

    at com.intellij.codeInsight.completion.AsyncCompletion.lambda$tryReadOrCancel$5(CompletionThreading.java:162)

    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1075)

    at com.intellij.codeInsight.completion.AsyncCompletion.tryReadOrCancel(CompletionThreading.java:160)

    at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$startContributorThread$8(CodeCompletionHandlerBase.java:369)

    at io.opentelemetry.context.Context.lambda$wrap$1(Context.java:212)

    at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$0(CompletionThreading.java:85)

    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:192)

    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)

    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)

    at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)

    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)

    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:78)

    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:179)

    at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$1(CompletionThreading.java:81)

    at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:249)

    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)

    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)

    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)

    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)

    at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)

    at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)

    at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)

    at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)

    at java.base/java.lang.Thread.run(Thread.java:840)
```

### Steps to reproduce

Currently unknown, as the error was thrown in silent and noticed much later. Will update once more information comes up.

### Plugin version

0.0.3

### Intellij version

2023.2.3

### Operating System

None

**Comment by johmara** [comment]
Can you please try this again in version 0.0.4 and see if it is fixed?

**Comment by Kevin3112** [comment]
I talked to the student who ran into the problem recently, and he mentioned that this error hasn't occurred again ever since it was thrown the first time. I'm still unaware how to reproduce it. 
I'm not sure, but I think he also upgraded to 0.0.4. Will keep you posted!
